language: ruby
cache: bundler
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2

install:
    # update aptitude
    - sudo apt-get update -y

    # install aptitude packages
    - LDFLAGS=-lm sudo apt-get install -y $(< requirements)

    # install ruby gems
    - gem install bundler
    - bundle install

script:
    # creating and activating virtualenv
    - virtualenv -p python2.7 --distribute rubythumbor
    - source ./rubythumbor/bin/activate

    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors

    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import thumbor; print(os.path.dirname(thumbor.__file__))")

    # finally run tests
    - rake spec

os:
  - linux
  - osx
